"""add product image attribution

Revision ID: b6de97a2d3b3
Revises: 215b0cd2b61b
Create Date: 2026-09-19 07:23:59.955297+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b6de97a2d3b3'
down_revision: str | None = '215b0cd2b61b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_source', sa.String(length=80), nullable=True))
    op.add_column('products', sa.Column('image_source_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('image_license', sa.String(length=80), nullable=True))
    op.add_column('products', sa.Column('image_author', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_author')
    op.drop_column('products', 'image_license')
    op.drop_column('products', 'image_source_url')
    op.drop_column('products', 'image_source')
    # ### end Alembic commands ###
