"""add quote subdivision code

Revision ID: ecfe49743e19
Revises: 493db1b00d94
Create Date: 2026-09-19 20:25:16.109069+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ecfe49743e19'
down_revision: str | None = '493db1b00d94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('subdivision_code', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_quotes_subdivision_code'), 'quotes', ['subdivision_code'], unique=False)
    # 回填：既有報價從報價者的個人檔案補上 ISO 代碼。
    # 沒有這段的話，所有舊報價都會查不到——而這支 migration 的目的
    # 正是讓區域篩選查得到東西。
    op.execute(
        """
        UPDATE quotes q
           SET subdivision_code = u.subdivision_code
          FROM users u
         WHERE u.id = q.user_id
           AND u.subdivision_code IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_subdivision_code'), table_name='quotes')
    op.drop_column('quotes', 'subdivision_code')
    # ### end Alembic commands ###
