"""initial schema

Revision ID: 215b0cd2b61b
Revises: 
Create Date: 2026-09-19 04:06:34.377364+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '215b0cd2b61b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=160), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_data_sources_key'))
    )
    op.create_index(op.f('ix_data_sources_country_code'), 'data_sources', ['country_code'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'phone_change', name='otp_purpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index('ix_otp_codes_phone_created_at', 'otp_codes', ['phone', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('vegetable', 'fruit', 'flower', 'grain', 'livestock', 'fishery', 'other', name='product_category'), nullable=False),
    sa.Column('default_unit', sa.String(length=16), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_popularity'), 'products', ['popularity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('consumer', 'farmer', 'trader', name='user_role'), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='ingest_status'), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('markets_created', sa.Integer(), nullable=False),
    sa.Column('mappings_created', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_ingest_runs_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_runs'))
    )
    op.create_index('ix_ingest_runs_source_id_started_at', 'ingest_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_markets_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_markets_source_id_external_id')
    )
    op.create_index(op.f('ix_markets_country_code'), 'markets', ['country_code'], unique=False)
    op.create_index('ix_markets_country_code_name', 'markets', ['country_code', 'name'], unique=False)
    op.create_index(op.f('ix_markets_region'), 'markets', ['region'], unique=False)
    op.create_index(op.f('ix_markets_source_id'), 'markets', ['source_id'], unique=False)
    op.create_table('product_names',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_names_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_names')),
    sa.UniqueConstraint('product_id', 'locale', 'name', name='uq_product_names_product_id_locale_name')
    )
    op.create_index('ix_product_names_locale_name', 'product_names', ['locale', 'name'], unique=False)
    op.create_index(op.f('ix_product_names_product_id'), 'product_names', ['product_id'], unique=False)
    op.create_table('product_source_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(length=80), nullable=False),
    sa.Column('external_name', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('source_unit', sa.String(length=32), nullable=True),
    sa.Column('unit_factor', sa.Float(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_source_mappings_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_product_source_mappings_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_source_mappings')),
    sa.UniqueConstraint('source_id', 'external_code', name='uq_product_source_mappings_source_id_external_code')
    )
    op.create_index(op.f('ix_product_source_mappings_product_id'), 'product_source_mappings', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_source_mappings_source_id'), 'product_source_mappings', ['source_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('official_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('price_avg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_mid', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('volume_unit', sa.String(length=16), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['product_source_mappings.id'], name=op.f('fk_official_prices_mapping_id_product_source_mappings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_official_prices_market_id_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_official_prices_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_official_prices_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_official_prices')),
    sa.UniqueConstraint('source_id', 'market_id', 'mapping_id', 'trade_date', 'grade', name='uq_official_prices_source_market_mapping_date_grade')
    )
    op.create_index('ix_official_prices_market_id_trade_date', 'official_prices', ['market_id', 'trade_date'], unique=False)
    op.create_index('ix_official_prices_product_id_trade_date', 'official_prices', ['product_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_official_prices_source_id'), 'official_prices', ['source_id'], unique=False)
    op.create_index('ix_official_prices_trade_date', 'official_prices', ['trade_date'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=True),
    sa.Column('side', sa.Enum('sell', 'buy', name='quote_side'), nullable=False),
    sa.Column('role_snapshot', sa.Enum('consumer', 'farmer', 'trader', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'withdrawn', 'hidden', name='quote_status'), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('min_order', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('location_text', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_phone_public', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_quotes_market_id_markets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quotes_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quotes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    op.create_index('ix_quotes_country_code_status', 'quotes', ['country_code', 'status'], unique=False)
    op.create_index('ix_quotes_product_id_status_created_at', 'quotes', ['product_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_quotes_region'), 'quotes', ['region'], unique=False)
    op.create_index('ix_quotes_status_valid_until', 'quotes', ['status', 'valid_until'], unique=False)
    op.create_index('ix_quotes_user_id_created_at', 'quotes', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_user_id_created_at', table_name='quotes')
    op.drop_index('ix_quotes_status_valid_until', table_name='quotes')
    op.drop_index(op.f('ix_quotes_region'), table_name='quotes')
    op.drop_index('ix_quotes_product_id_status_created_at', table_name='quotes')
    op.drop_index('ix_quotes_country_code_status', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_official_prices_trade_date', table_name='official_prices')
    op.drop_index(op.f('ix_official_prices_source_id'), table_name='official_prices')
    op.drop_index('ix_official_prices_product_id_trade_date', table_name='official_prices')
    op.drop_index('ix_official_prices_market_id_trade_date', table_name='official_prices')
    op.drop_table('official_prices')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_product_source_mappings_source_id'), table_name='product_source_mappings')
    op.drop_index(op.f('ix_product_source_mappings_product_id'), table_name='product_source_mappings')
    op.drop_table('product_source_mappings')
    op.drop_index(op.f('ix_product_names_product_id'), table_name='product_names')
    op.drop_index('ix_product_names_locale_name', table_name='product_names')
    op.drop_table('product_names')
    op.drop_index(op.f('ix_markets_source_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_region'), table_name='markets')
    op.drop_index('ix_markets_country_code_name', table_name='markets')
    op.drop_index(op.f('ix_markets_country_code'), table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_ingest_runs_source_id_started_at', table_name='ingest_runs')
    op.drop_table('ingest_runs')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_popularity'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_otp_codes_phone_created_at', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_data_sources_country_code'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
