"""add product favorites

Revision ID: 050a08e79979
Revises: ef9c3614bb57
Create Date: 2026-09-19 19:23:39.110682+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '050a08e79979'
down_revision: str | None = 'ef9c3614bb57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 只建立 product_favorites。autogenerate 另外想改 users 兩個欄位的
    # server_default，那是它比對不出 Python 端 default 的誤判，已移除。
    op.create_table('product_favorites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_favorites_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_favorites')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_product_favorites_user_id_product_id')
    )
    op.create_index(op.f('ix_product_favorites_product_id'), 'product_favorites', ['product_id'], unique=False)
    op.create_index('ix_product_favorites_user_id_created_at', 'product_favorites', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_favorites_user_id_created_at', table_name='product_favorites')
    op.drop_index(op.f('ix_product_favorites_product_id'), table_name='product_favorites')
    op.drop_table('product_favorites')
    # ### end Alembic commands ###
